services:
  portfolio:
    build:
        context: ./packages/portfolio
        target: base
    ports:
      - "8000:80"
    networks:
      - portfolionet
  listassist:
    image: nginx:alpine
    volumes:
      - ./packages/listassist:/usr/share/nginx/html
    working_dir: /app
    ports:
      - "8001:80"
    networks:
      - portfolionet
networks:
  portfolionet:
    driver: bridge
    ipam:
      config:
        - subnet: 172.30.0.0/24